# Generated by Django 3.0.5 on 2020-04-12 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_form',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user_form',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='user_form',
            name='signup_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user_form',
            name='email_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
