# Generated by Django 3.0.5 on 2020-04-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200414_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_form',
            name='image',
            field=models.ImageField(default='', upload_to='home/sujan/PycharmProjects/learndjango/image_forgery/accounts'),
        ),
    ]
