# Generated by Django 3.0.5 on 2020-04-14 15:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200414_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_form',
            old_name='person_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user_form',
            name='image',
        ),
        migrations.AddField(
            model_name='user_form',
            name='confirm_password',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user_form',
            name='signup_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user_form',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
