# Generated by Django 3.0.5 on 2020-04-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200414_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_form',
            name='image',
            field=models.ImageField(default='', upload_to='home/sujan/PycharmProjects/learndjango/image_forgery/accounts'),
        ),
    ]
