# Generated by Django 3.0.5 on 2020-04-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_form_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_form',
            name='last_login',
        ),
        migrations.AddField(
            model_name='user_form',
            name='profile_pic',
            field=models.ImageField(default='1.jpg', upload_to='profile_pics'),
        ),
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
