# Generated by Django 3.0.5 on 2020-04-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200414_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_form',
            name='profile_pic',
            field=models.ImageField(default='1.jpg', upload_to='profile_pics'),
        ),
    ]
