# Generated by Django 3.0.5 on 2020-04-18 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_form_profile_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_form',
        ),
    ]
