# Generated by Django 3.0.5 on 2020-04-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='detectedimages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sample_image', models.ImageField(default='1.jpg', upload_to='profile_pics')),
            ],
        ),
    ]
