# Generated by Django 3.0.5 on 2020-04-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectedimages',
            name='sample_image',
            field=models.ImageField(default='1.jpg', upload_to='images'),
        ),
    ]
