# Generated by Django 3.0.5 on 2020-04-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0002_auto_20200423_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectedimages',
            name='sample_image',
            field=models.ImageField(default='1.jpg', help_text='JPG or PNG', upload_to='images'),
        ),
    ]
