# Generated by Django 3.0.5 on 2020-04-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0003_auto_20200423_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectedimages',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
